- name: Install nginx
  apt: name=nginx update_cache=yes state=present
  become: True

- name: Disable the default website
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent
  become: True

- name: Copy the application nginx configuration file
  template: src=templates/nginx.conf dest=/etc/nginx/sites-available/nginx.conf
  become: True

- name: Enable the website
  file: src=/etc/nginx/sites-available/nginx.conf dest=/etc/nginx/sites-enabled/nginx.conf state=link
  become: True

- name: Reload nginx
  service: name=nginx state=reloaded
  become: True

- name: Restart nginx
  service: name=nginx state=restarted
  become: True
