- name: Configure the Python RestAPI server
  hosts: 127.0.0.1
  connection: local
  roles:
    - common
    - virtualenv
    - nginx
    - application
    - supervisor
  vars:
    - code_dir_name: "python-restapi-boilerplate"
    - branch_name: "develop"
    - venv_name: "venv"
    - gunicorn_num_workers: 2
    - app_port: 3000
    - app_debug: False