# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  # Create the python restapi boilerplate ubuntu VM
  config.vm.define "python_restapi" do |python_restapi|
    python_restapi.vm.box = "bento/ubuntu-16.04"
    python_restapi.vm.synced_folder "..", "/home/vagrant/python-restapi-boilerplate"

    python_restapi.vm.network "forwarded_port", guest: 80, host: 8080

    python_restapi.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end